name: 'Publish packages'

on:
  release:
    types: [published]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.4
    - name: Zip up files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r itertools.zip .
    - name: Upload to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: itertools
        path: ${{ github.workspace }}/itertools.zip
    - name: Publish to Haxelib
      run: haxelib submit itertools.zip ${{ secrets.HAXELIB_NAME }} ${{ secrets.HAXELIB_PASS }} --always
