name: 'Run tests'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/**'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
      - name: Install dependencies
        run: |
          haxelib --always install all
      - name: Run tests
        run: |
          haxe tests.hxml
